# Generated by Django 4.2.17 on 2024-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderHomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('little_text', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='sliders')),
            ],
            options={
                'verbose_name': 'слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
