# Generated by Django 4.2.17 on 2024-12-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_sliderhomepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='service'),
        ),
    ]
