# Generated by Django 4.2.17 on 2024-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='payMethod')),
            ],
            options={
                'verbose_name': 'способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
    ]
