# Generated by Django 4.2.17 on 2024-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='phone1',
            field=models.CharField(help_text='996770770770', max_length=20, verbose_name='Телефон №1'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='phone2',
            field=models.CharField(blank=True, help_text='996770770770', max_length=20, null=True, verbose_name='Телефон №2'),
        ),
    ]
