# Generated by Django 4.2.17 on 2024-12-23 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_partners_phone1_alter_partners_phone2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='category',
        ),
        migrations.AddField(
            model_name='partners',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категории'),
        ),
    ]
