# Generated by Django 4.2.17 on 2024-12-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_partners_category_partners_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoVa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('description', models.TextField(verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
    ]
