# Generated by Django 4.2.17 on 2024-12-27 13:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_vova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vova',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
